default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER']%>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: qbo-cambodia_development

test:
  <<: *default
  database: qbo-cambodia_test

staging:
  <<: *default

production:
  <<: *default
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host:     <%= ENV['DATABASE_HOST']%>
  username: <%= ENV['DATABASE_USER']%>
  port:     <%= ENV['DATABASE_PORT']%>
